spring.application.name=tradingview

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# web admin password Abcdefgh1234
spring.h2.console.settings.web-admin-password=8ad07cf3e701b4e06e6d31d3b98c4d384d46339b5cb8a4636c16c1a1028186501c62a347fd1f8f1a6459a3b955c02a1ea1ab298765cdcf994ee7bfc313194cca
spring.h2.console.settings.web-allow-others=true

spring.datasource.url=jdbc:h2:file:/Users/idea/tradingview/h2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database=h2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

logging.level.home=debug
logging.pattern.dateformat=HH:mm:ss.SSS

# To trigger shutdown, send a POST request to the /actuator/shutdown endpoint
management.endpoint.shutdown.access=unrestricted