CREATE TABLE IF NOT EXISTS table1 (
    symbol VARCHAR(7),
    intv INTEGER,
    tim3 BIGINT,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    ma1 REAL,
    ma2 REAL,
    ma3 REAL,
    ma4 REAL,
    ma5 REAL,
    volume INTEGER,
    basis REAL,
    upper REAL,
    lower REAL,
    histogram REAL,
    macd REAL,
    signal REAL,
    percentk REAL,
    percentd REAL,
    rsi REAL,
    rsibasedma REAL,
    PRIMARY KEY (symbol, intv, tim3)
);