### SOXL start with 1m
POST http://localhost:8080/download-data
Content-Type: application/json

{
  "activatePoint": { "x": -2808, "y": -971 },
  "intervalDropdowns": [
    {
      "1d": "...",
      "scrollTimes": 8,
      "downArrow": { "x": -3546, "y": -965 },
      "menuItem": { "x": -3532, "y": -169 }
    }
  ],
  "scrollScreen": {
    "clickAt": { "x": -3777, "y": 276 },
    "scrollTo": { "x": -2441, "y": 276 }
  },
  "exportDropdown": {
    "clickAt": { "x": -2202, "y": -968 },
    "exportChartData": { "x": -2120 , "y": -765 },
    "exportButton": { "x": -2754 , "y": 107 }
  }
}

###
POST http://localhost:8080/actuator/shutdown

###
GET http://localhost:8080/actuator