### SOXL start with 1m
POST http://localhost:8080/download-data
Content-Type: application/json

{
  "intervalDropdowns": [
    {
      "downArrow": { "x": -3572, "y": -261 },
      "menuItem": { "x": -3558, "y": 9 }
    },
    {
      "downArrow": { "x": -3544 , "y": -261 },
      "menuItem": { "x": 3520, "y": 41 }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    },
    {
      "downArrow": { "x": , "y": },
      "menuItem": { "x": , "y": }
    }
  ],
  "scrollScreen": {
    "clickAt": { "x": -3777, "y": 326 },
    "scrollTo": { "x": -2515, "y": 326 }
  },
  "exportDropdown": {
    "clickAt": { "x": -2171, "y": -260 },
    "exportChartData": { "x": -2110 , "y": -58 },
    "exportButton": { "x": -2749 , "y": 339 }
  }
}